# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run test -- --browser chrome --headless
  displayName: 'npm install and run test in chrome'

- task: PublishTestResults@2
  displayName: 'Publish Test Results **/test-output-*.xml '
  inputs:
    testResultsFiles: '**/test-output-*.xml '

- task: PublishCucumberReport@1
  displayName: 'Publish Cucumber Report'
  inputs:
    jsonDir: '$(System.DefaultWorkingDirectory)/_stepin105057_DanfossCypressBDD/cypress/cucumber-json'
    outputPath: '$(System.DefaultWorkingDirectory)/_stepin105057_DanfossCypressBDD/cypress/cucumber-json'